// Generated by CoffeeScript 1.9.1
(function() {
  var appendCSS, evalAnnotations, evaluableTag, extend, getAnnotations, getElements, hideTag;

  extend = require('extend');

  appendCSS = require('append-css');

  hideTag = function(qs) {
    return appendCSS(qs + " {\n  width     : 0;\n  height    : 0;\n  visibility:hidden;\n}");
  };

  evalAnnotations = function(qs, elmSlector) {
    var annotations;
    hideTag(qs);
    annotations = document.querySelectorAll(qs);
    return [].map.call(annotations, function(annot) {
      var data, elm;
      elm = elmSlector(annot);
      data = eval("(" + (annot.getAttribute('data-eval')) + ")");
      return {
        ref: annot,
        elm: elm,
        data: data
      };
    });
  };

  getAnnotations = function(qs) {
    return evalAnnotations(qs, function(annot) {
      var elm;
      elm = annot.nextSibling;
      while ((elm != null ? elm.nodeType : void 0) === Node.TEXT_NODE) {
        elm = elm.nextSibling;
      }
      return elm;
    });
  };

  getElements = function(qs) {
    return evalAnnotations(qs, function(annot) {
      return annot;
    });
  };

  evaluableTag = {
    getAnnotations: getAnnotations,
    getElements: getElements
  };

  module.exports = evaluableTag;

}).call(this);
