// Generated by CoffeeScript 1.9.1
(function() {
  var EvaluableTag, _eval, _hide, appendCSS, evalAnnotationsBy, evalBy, extend, hidQueries;

  extend = require('extend');

  appendCSS = require('append-css');

  hidQueries = [];

  _hide = function(qs) {
    return appendCSS(qs + " {\n  width      : 0;\n  height     : 0;\n  line-height: 0;\n  visibility : hidden;\n  margin     : 0;\n  padding    : 0;\n}");
  };

  _eval = function(qs, select) {
    var tags;
    tags = document.querySelectorAll(qs);
    return [].map.call(tags, function(tag) {
      var res, target;
      target = select(tag);
      res = eval("(" + (tag.getAttribute('data-eval')) + ")");
      return {
        annotation: tag,
        annotated: target,
        result: res
      };
    });
  };

  evalAnnotationsBy = function(qs) {
    if (hidQueries.indexOf(qs) === -1) {
      hidQueries.push(qs);
      _hide(qs);
    }
    return _eval(qs, function(tag) {
      var target;
      target = tag.nextSibling;
      while ((target != null ? target.nodeType : void 0) === Node.TEXT_NODE) {
        target = target.nextSibling;
      }
      return target;
    });
  };

  evalBy = function(qs) {
    return _eval(qs, function(tag) {
      return tag;
    });
  };

  EvaluableTag = {
    evalAnnotationsBy: evalAnnotationsBy,
    evalBy: evalBy
  };

  module.exports = EvaluableTag;

}).call(this);
